//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dist23Bridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeLink
    {
        public int link_id { get; set; }
        public Nullable<int> vol_id { get; set; }
        public Nullable<int> bridge_id { get; set; }
        public Nullable<System.DateTime> DateAssign { get; set; }
        public Nullable<System.DateTime> FirstLetterSent { get; set; }
        public Nullable<System.DateTime> FirstResponse { get; set; }
        public Nullable<System.DateTime> FirstVisit { get; set; }
        public Nullable<System.DateTime> FirstMeeting { get; set; }
    
        public virtual Bridger Bridger { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
