//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dist23Bridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jail()
        {
            this.Bridgers = new HashSet<Bridger>();
        }
    
        public int jail_id { get; set; }
        public string JailName { get; set; }
        public string JailAddress { get; set; }
        public string JailContact { get; set; }
        public string JailContPhone { get; set; }
        public string JailContEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bridger> Bridgers { get; set; }
    }
}
